### ISSUE TITLE
PSK mandatory or optional

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/authserver#15]
Our understanding is that it is/will be a TC discussion point to determine whether support for RadSec pre-shared keys should stay optional or be made mandatory. Formal resolution on this will be needed before it can be determined how to handle the RadSec requirements surrounding PSK functionality.

**Comment by ajlaing** [comment]
Hold on this. RADIUS is outdated and the TC is considering replacing with DIAMETER, which includes transport protections. The TC also plans additional discussion regarding whether RADIUS/DIAMETER is required, or to allow other authentication server messaging approaches (TBD) to generalize the use of this PP by a more general class of products (such as PAM).

The use of PSK alone is not recommended for traffic protection. Currently support for certificate-based authentication (Cyber) is mandatory in the PP, and while we are suggesting OTP and PSK options to the TC in order to support combined authentication mechanisms defined in NIST SP 800-63-3 Part B (specifically, Cyber+PW, Cyber+OTP, Cyber+OTP+PW), it is not the intention to relax the requirement for Certificate-based support.

**Comment by jfisherbah** [comment]
Believe this has been resolved because RadSec is selection-based in the latest draft, as are pre-shared keys. Closing.
